#!/usr/bin/env sh

# Run pre-commit checks.
set -e

echo "Running environment checks..."
chiva env check

echo "Formatting code..."
bun run format

echo "Running lint checks..."
bun run lint

echo "Running type checks..."
bun run typecheck

echo "Building project..."
bun run build

echo "Pre-commit checks passed."
